// Authentication
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SET_TOKEN = "SET_TOKEN";
export const SIGN_OUT = "SIGN_OUT";

// User
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER_AVATAR = "UPDATE_CURRENT_USER_AVATAR";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

// Scorecard
export const CREATE_NEW_SCORECARD = "CREATE_NEW_SCORECARD";
export const CREATE_NEW_SCORECARD_FROM_TEMPLATE = "CREATE_NEW_SCORECARD_FROM_TEMPLATE";
export const GET_ALL_SCORECARDS = "GET_ALL_SCORECARDS";
export const SET_SCORECARD = "SET_SCORECARD";

// Perspective
export const CREATE_NEW_PERSPECTIVE = "CREATE_NEW_PERSPECTIVE";
export const GET_ALL_PERSPECTIVES = "GET_ALL_PERSPECTIVES";

// Objevtive
export const CREATE_NEW_OBJECTIVE = "CREATE_NEW_OBJECTIVE";
export const GET_ALL_OBJECTIVES = "GET_ALL_OBJECTIVES";
export const SET_OBJECTIVES = "SET_OBJECTIVES";
