// Authentication
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SET_TOKEN = "SET_TOKEN";
export const SIGN_OUT = "SIGN_OUT";

// User
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER_AVATAR = "UPDATE_CURRENT_USER_AVATAR";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

// Scorecard
export const CREATE_NEW_SCORECARD = "CREATE_NEW_SCORECARD";
export const CREATE_NEW_SCORECARD_FROM_TEMPLATE =
  "CREATE_NEW_SCORECARD_FROM_TEMPLATE";
export const GET_ALL_SCORECARDS = "GET_ALL_SCORECARDS";
export const GET_SCORECARD = "GET_SCORECARD";
export const SET_SCORECARD = "SET_SCORECARD";
export const SET_SCORECARDS = "SET_SCORECARDS";
export const DELETE_SCORECARD = "DELETE_SCORECARD";
export const GET_PERSPECTIVES_OF_SCORECARD = "GET_PERSPECTIVES_OF_SCORECARD";
export const SET_PERSPECTIVES_OF_SCORECARD = "SET_PERSPECTIVES_OF_SCORECARD";
export const ASSIGN_EMPLOYEE_TO_SCORECARD = "ASSIGN_EMPLOYEE_TO_SCORECARD";
export const UPDATE_SCORECARD = "UPDATE_SCORECARD";
export const GET_ASSIGNED_EMPLOYEES_OF_SCORECARD =
  "GET_ASSIGNED_EMPLOYEES_OF_SCORECARD";
export const SET_ASSIGNED_EMPLOYEES_OF_SCORECARD =
  "SET_ASSIGNED_EMPLOYEES_OF_SCORECARD";
export const GET_ASSIGNED_SCORECARDS = "GET_ASSIGNED_SCORECARDS";
export const SET_ASSIGNED_SCORECARDS = "SET_ASSIGNED_SCORECARDS";

// Perspective
export const CREATE_NEW_PERSPECTIVE = "CREATE_NEW_PERSPECTIVE";
export const GET_ALL_PERSPECTIVES = "GET_ALL_PERSPECTIVES";
export const GET_OBJECTIVES_OF_PERSPECTIVE = "GET_OBJECTIVES_OF_PERSPECTIVE";
export const SET_OBJECTIVES_OF_PERSPECTIVE = "SET_OBJECTIVES_OF_PERSPECTIVE";
export const GET_PERSPECTIVE = "GET_PERSPECTIVE";
export const SET_PERSPECTIVE = "SET_PERSPECTIVE";
export const DELETE_PERSPECTIVE = "DELETE_PERSPECTIVE";
export const UPDATE_PERSPECTIVE = "UPDATE_PERSPECTIVE";
export const ASSIGN_EMPLOYEE_TO_PERSPECTIVE = "ASSIGN_EMPLOYEE_TO_PERSPECTIVE";
export const GET_ASSIGNED_EMPLOYEES_OF_PERSPECTIVE =
  "GET_ASSIGNED_EMPLOYEES_OF_PERSPECTIVE";
export const SET_ASSIGNED_EMPLOYEES_OF_PERSPECTIVE =
  "SET_ASSIGNED_EMPLOYEES_OF_PERSPECTIVE";
export const GET_ASSIGNED_PERSPECTIVES = "GET_ASSIGNED_PERSPECTIVES";
export const SET_ASSIGNED_PERSPECTIVES = "SET_ASSIGNED_PERSPECTIVES";

// Objevtive
export const CREATE_NEW_OBJECTIVE = "CREATE_NEW_OBJECTIVE";
export const SET_OBJECTIVES = "SET_OBJECTIVES";
export const SET_OBJECTIVE = "SET_OBJECTIVE";
export const GET_KPIS_OF_OBJECTIVE = "GET_KPIS_OF_OBJECTIVE";
export const SET_KPIS_OF_OBJECTIVE = "SET_KPIS_OF_OBJECTIVE";
export const GET_OBJECTIVE = "GET_OBJECTIVE";
export const DELETE_OBJECTIVE = "DELETE_OBJECTIVE";
export const UPDATE_OBJECTIVE = "UPDATE_OBJECTIVE";
export const ASSIGN_EMPLOYEE_TO_OBJECTIVE = "ASSIGN_EMPLOYEE_TO_OBJECTIVE";
export const GET_ASSIGNED_EMPLOYEES_OF_OBJECTIVE =
  "GET_ASSIGNED_EMPLOYEES_OF_OBJECTIVE";
export const SET_ASSIGNED_EMPLOYEES_OF_OBJECTIVE =
  "SET_ASSIGNED_EMPLOYEES_OF_OBJECTIVE";
export const GET_ASSIGNED_OBJECTIVES = "GET_ASSIGNED_OBJECTIVES";
export const SET_ASSIGNED_OBJECTIVES = "GET_ASSIGNED_OBJECTIVES";

// KPI
export const CREATE_NEW_KPI = "CREATE_NEW_KPI";
export const SET_KPI = "SET_KPI";
export const GET_KPI = "GET_KPI";
export const DELETE_KPI = "DELETE_KPI";
export const UPDATE_KPI = "UPDATE_KPI";
export const ASSIGN_EMPLOYEE_TO_KPI = "ASSIGN_EMPLOYEE_TO_KPI";
export const GET_ASSIGNED_KPIS = "GET_ASSIGNED_KPIS";
export const SET_ASSIGNED_KPIS = "SET_ASSIGNED_KPIS";
export const GET_ASSIGNED_EMPLOYEES_OF_KPI = "GET_ASSIGNED_EMPLOYEES_OF_KPI";
export const SET_ASSIGNED_EMPLOYEES_OF_KPI = "SET_ASSIGNED_EMPLOYEES_OF_KPI";
export const CREATE_KPI_VALUE = "CREATE_KPI_VALUE";
export const GET_KPI_VALUES = "GET_KPI_VALUES";
export const SET_KPI_VALUES = "SET_KPI_VALUES";

// Workspace
export const ADD_MEMBER = "ADD_MEMBER";
export const GET_MEMBERS = "GET_MEMBERS";
export const REMOVE_MEMBER = "REMOVE_MEMBER";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
export const SET_MEMBERS = "SET_MEMBERS";
